### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by AnandhaPriyaK** [extent-framework/extentreports-java#256]
Hi all,

I am using testng-version 7.1.0 & extentreports-version 4.0.7, getting concurrentModificationException in following line.
Please help me fix this issue.

My Code: ExtentManager.getTestStep().log(Status.INFO, m);

Error:
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at com.aventstack.extentreports.ExtentObservable.collectRunInfo(ExtentObservable.java:465)
at com.aventstack.extentreports.ExtentObservable.addLog(ExtentObservable.java:309)
at com.aventstack.extentreports.ExtentTest.addLog(ExtentTest.java:359)
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:308)
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:333)
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:352)

Note: i use DataProvider, Multithreading.

**Comment by anshooarora** [comment]
@AnandhaPriyaK 

Can you please upgrade to version 5 and let me know if you still encounter this?  `4.x` is no longer supported..
