### ISSUE TITLE
ConcurrentModificationException still present

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports-java#290]
version 5.0.7

`java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1388)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.aventstack.extentreports.model.ReportStats.update(ReportStats.java:49)
	at com.aventstack.extentreports.model.Report.refresh(Report.java:50)
	at com.aventstack.extentreports.AbstractProcessor.onFlush(AbstractProcessor.java:82)
	at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:284)`

**Comment by anshooarora** [comment]
Please check with `5.0.8-SNAPSHOT`.  My cli isn't running some of the new tests I've added but running in Eclipse caught these exceptions.  Fixed in https://github.com/extent-framework/extentreports-java/commit/215216020d25778a3cc12c5e33066c197c86e53f.

**Comment by mmajcherczyk** [comment]
in v5.0.8 i still have it 

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1388)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.aventstack.extentreports.model.ReportStats.update(ReportStats.java:49)
	at com.aventstack.extentreports.model.Report.refresh(Report.java:52)
	at com.aventstack.extentreports.AbstractProcessor.onFlush(AbstractProcessor.java:82)
	at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:284)
```
