### ISSUE TITLE
Spark Reporter - The Dashboard page is in standard theme when the theme is dark

### ISSUE THREAD

**Issue by vali92** [extent-framework/extentreports-java#33]
Extent version: 4.0.8-SNAPSHOT

he Dashboard page is in standard theme when the theme is dark.

**Comment by anshooarora** [comment]
Fixed, and changes saved to the latest snapshot.

**Comment by vali92** [comment]
@anshooarora , there is an issue with this, the report is generated but the page cannot be accessed. 

[Thread-4] ERROR freemarker.runtime  - Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> theme  [in template "spark/dashboard.ftl" at line 36, column 39]

----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${theme}  [in template "spark/dashboard.ftl" at line 36, column 37]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
	at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at freemarker.template.Template.process(Template.java:325)
	at com.aventstack.extentreports.reporter.BasicFileReporter.processTemplate(BasicFileReporter.java:295)
	at com.aventstack.extentreports.reporter.ExtentSparkReporter.flush(ExtentSparkReporter.java:66)
	at com.aventstack.extentreports.ExtentObservable.lambda$notifyReporters$21(ExtentObservable.java:544)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.aventstack.extentreports.ExtentObservable.notifyReporters(ExtentObservable.java:544)
	at com.aventstack.extentreports.ExtentObservable.flush(ExtentObservable.java:429)
	at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:275)
	at frameworkSrc.extentReports.TestListener.onFinish(TestListener.java:77)
	at org.testng.TestRunner.fireEvent(TestRunner.java:874)
	at org.testng.TestRunner.afterRun(TestRunner.java:837)
	at org.testng.TestRunner.run(TestRunner.java:592)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
	at org.testng.SuiteRunner.run(SuiteRunner.java:302)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at frameworkSrc.userInterface.Screen_4$4.run(Screen_4.java:400)
	at java.lang.Thread.run(Unknown Source)
[2019-01-18 17:03:41] [SEVERE ] An exception occurred

**Comment by anshooarora** [comment]
Please do a force update of snapshots.. this issue will go away.
