### ISSUE TITLE
Merging of 2 html spark reports

### ISSUE THREAD

**Issue by ashanirmala7** [extent-framework/extentreports-java#331]
Dear team, I would like to combine the current run html results with the previous run file. I tried the options given in the docs as

ExtentSparkReporter spark = new ExtentSparkReporter("spark.html");
JsonFormatter json = new JsonFormatter("extent.json");
ExtentReports extent = new ExtentReports();
extent.createDomainFromJsonArchive("extent.json");
extent.attachReporter(json, spark);

But i am getting the below error- Could you please help me on this.

java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @13c27452
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:931)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.aventstack.extentreports.append.JsonDeserializer.deserialize(JsonDeserializer.java:30)
	at com.aventstack.extentreports.append.RawEntityConverter.convertAndApply(RawEntityConverter.java:27)
	at com.aventstack.extentreports.AbstractProcessor.convertRawEntities(AbstractProcessor.java:98)
	at com.aventstack.extentreports.ExtentReports.createDomainFromJsonArchive(ExtentReports.java:372)
	at com.aventstack.extentreports.ExtentReports.createDomainFromJsonArchive(ExtentReports.java:387)
	at common.utility.ExtentReportUtil.createReport(ExtentReportUtil.java:64)

**Comment by fatcatpl-sub** [comment]
Hi, did anyone come up with a workaround for this one? I happened upon it yesterday after update from jdk 11 to 17, and nothing seems to work. What am I missing? Any suggestion appreciated!

**Comment by anshooarora** [comment]
@fatcatpl-sub Was it working prior to the upgrade?

**Comment by fatcatpl-sub** [comment]
@anshooarora yeah, works fine with jdk 11. Unfortunately we're moving to jdk 17, so going back is not an option. Also, reports work fine if you remove the option co combine them into one html, as in: 

ExtentSparkReporter spark = new ExtentSparkReporter("spark.html");
ExtentReports extent = new ExtentReports();
extent.attachReporter(spark);

That part is alright. All fails during json deserialization. And without it, with e2e pipelines containing whole sets of classes, we either end up with dozen report files per test run or one, with last method performed only.
I'm still wondering if anyone else can reproduce that, as I only managed to find this issue report here and one on [Stack](https://stackoverflow.com/questions/76173330/how-to-merge-reports-in-v5-of-extent-reports), or if I'm missing something and it's a problem on my side, but I can't think of anything else.

**Comment by anshooarora** [comment]
Thanks for the details.  Do see a possible fix Gson library fix available (below), will look into it.

Gson: https://github.com/google/gson/issues/1979

**Comment by anshooarora** [comment]
Spent some time on this today - and have found out the issue.  It's not a trivial fix but I will try to complete this task by sometime next week.

**Comment by anshooarora** [comment]
This change is available starting the current SNAPSHOT:

https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports/5.1.1-SNAPSHOT/

```
<groupId>com.aventstack</groupId>
<artifactId>extentreports</artifactId>
<version>5.1.1-SNAPSHOT</version>
```

@fatcatpl-sub Can you please check if this works with your current setup?

**Comment by fatcatpl-sub** [comment]
@anshooarora I can confirm the change works correctly with my setup. 

I installed .jar in my local maven repo, ran a few test classes - both .html and .json were created successfully with all data intact. HTML file contained all reports generated during tests.
Let me know if you have any additional questions. And thank you very much!

**Comment by anshooarora** [comment]
@fatcatpl-sub thank you for checking, much appreciated!  I will include this fix as part of the next release.
