### ISSUE TITLE
java.lang.NoSuchFieldError: VERSION_2_3_30

### ISSUE THREAD

**Issue by saro011** [extent-framework/extentreports-java#396]
im getting this issue 
java.lang.NoSuchFieldError: VERSION_2_3_30
	at com.aventstack.extentreports.reporter.AbstractFileReporter.loadTemplateModel(AbstractFileReporter.java:54)
	at com.aventstack.extentreports.reporter.ExtentSparkReporter.start(ExtentSparkReporter.java:136)
	at com.aventstack.extentreports.reporter.ExtentSparkReporter$1.onSubscribe(ExtentSparkReporter.java:116)
	at io.reactivex.rxjava3.subjects.PublishSubject.subscribeActual(PublishSubject.java:133)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13262)
	at com.aventstack.extentreports.ReactiveSubject.attachReporter(ReactiveSubject.java:38)
	at com.aventstack.extentreports.ExtentReports.attachReporter(ExtentReports.java:66)
	at terabase.test.testStepDefinations.sample.fsc(sample.java:34)
	at ?.Fsc(file:///E:/selenium%20code/cucumberdemo/src/test/resources/feature/largeformat2.feature:23) 
maven project - used dependency

<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>5.1.0</version>
</dependency>

**Comment by anshooarora** [comment]
Can you share a small project/repo that reproduces this?

**Comment by gauravs158** [comment]
> Can you share a small project/repo that reproduces this?

Please check this: https://github.com/gauravs158/GSProject.git
